[package]
name = "frost-trusted-dealer-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
frost-ed25519 = "0.1.0"
thiserror = "1.0"
rand = "0.8"
hex = "0.4"
