[workspace]
members = [
    "participant",
    "trusted-dealer",
    "dkg",
    "coordinator", "tests"
]
default-members = ["participant",
    "trusted-dealer",
    "dkg",
    "coordinator", "tests"]
resolver = "2"
