[package]
name = "dkg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# frost-ed25519 = "0.4.0"
frost-ed25519 = { git = "https://github.com/ZcashFoundation/frost.git", rev = "30462edbfc74ef6ac988e2a967722602dfb86c21", features = ["serde"] }
hex = { version = "0.4", features = ["serde"] }
thiserror = "1.0"
rand = "0.8"
serde_json = "1.0"
itertools = "0.10.5"
exitcode = "1.1.2"
